spring:
  application:
    name: gateway-service-one
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<path>.*) , /$\{path}
        - id: account-service-one
          uri: lb://account-service-one
          predicates:
            - Path=/account-one/**
          filters:
            - RewritePath=/account-one/(?<path>.*) , /$\{path}
        - id: customer-service-one
          uri: lb://customer-service-one
          predicates:
            - Path=/customer-one/**
          filters:
            - RewritePath=/customer-one/(?<path>.*) , /$\{path}
            - name: Logging
              args:
                baseMessage: My Custom Message
                preLogger: true
                postLogger: false
        - id: product-service-one
          uri: lb://product-service-one
          predicates:
            - Path=/product-one/**
          filters:
            - RewritePath=/product-one/(?<path>.*), /$\{path}
        - id: order-service-one
          uri: lb://order-service-one
          predicates:
            - Path=/order-one/**
          filters:
            - RewritePath=/order-one/(?<path>.*) , /$\{path}



#logging.level.com.netflix: DEBUG

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE



