spring:
  application:
    name: resource-service-web-one
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:9191/oauth/authorize
      access-token-uri: http://localhost:9191/oauth/token
server:
  servlet:
    session:
      cookie:
        name: KSESSION
  port: 8086


logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
